version: "3"

services:
  web:
    build:
      context: .
    ports:
      - 8081:80
    environment:
      - DB_HOST=db
      - DB_USERNAME=db_covid
      - DB_PASSWORD=vdx91Dsa53F3
      - DB_NAME=db_covid
      - DB_PORT=5432
      - HTTP_PORT=80
    command: --runSeeder=covid_19_data.csv
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_covid
      - POSTGRES_DB=db_covid
      - POSTGRES_PASSWORD=vdx91Dsa53F3
  adminer:
    image: adminer
    ports:
      - 8080:8080
